export const PLACE_CONTENT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ARCHIVED: 'ARCHIVED',
} as const;

export const VERIFICATION_LEVEL = {
  UNVERIFIED: 'UNVERIFIED',
  AI_ESTIMATED: 'AI_ESTIMATED',
  COMMUNITY: 'COMMUNITY',
  CREATOR_VERIFIED: 'CREATOR_VERIFIED',
  OFFICIAL: 'OFFICIAL',
} as const;

export const VERIFICATION_DECISION = {
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  REVOKED: 'REVOKED',
  UPDATED: 'UPDATED',
} as const;

export const CONTENT_SOURCE_TYPE = {
  INTERNAL: 'INTERNAL',
  CREATOR: 'CREATOR',
  COMMUNITY: 'COMMUNITY',
  GOVERNMENT: 'GOVERNMENT',
  PARTNER: 'PARTNER',
  IMPORTED: 'IMPORTED',
} as const;
