from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "p2_template_engine"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "content_templates",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
        ),
        sa.Column(
            "name",
            sa.String(80),
            nullable=False,
        ),
        sa.Column(
            "slug",
            sa.String(100),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "description",
            sa.String(500),
        ),
        sa.Column(
            "icon",
            sa.String(100),
        ),
        sa.Column(
            "category",
            sa.String(100),
        ),
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            server_default="DRAFT",
        ),
        sa.Column(
            "current_version",
            sa.Integer(),
        ),
        sa.Column(
            "revision",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )

    op.create_index(
        "ix_content_templates_slug",
        "content_templates",
        ["slug"],
        unique=True,
    )

    op.create_index(
        "ix_content_templates_status",
        "content_templates",
        ["status"],
    )

    op.create_table(
        "template_groups",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
        ),
        sa.Column(
            "template_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "content_templates.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "label",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=False,
        ),
    )

    op.create_table(
        "template_fields",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
        ),
        sa.Column(
            "template_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "content_templates.id",
                ondelete="CASCADE",
            ),
            nullable=False,
        ),
        sa.Column(
            "group_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "template_groups.id",
                ondelete="SET NULL",
            ),
        ),
        sa.Column(
            "key",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.String(30),
            nullable=False,
        ),
        sa.Column(
            "label",
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            "help_text",
            sa.Text(),
        ),
        sa.Column(
            "required",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "translatable",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "config",
            postgresql.JSONB(),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "template_id",
            "key",
            name="uq_template_field_key",
        ),
    )


def downgrade():
    op.drop_table("template_fields")
    op.drop_table("template_groups")
    op.drop_index(
        "ix_content_templates_status",
        table_name="content_templates",
    )
    op.drop_index(
        "ix_content_templates_slug",
        table_name="content_templates",
    )
    op.drop_table("content_templates")
