from __future__ import annotations

from app.modules.social.domain.enums import (
    AccountAcceptanceAction,
    ContentStatus,
    ContentType,
    ContentVisibility,
    CreatorStatus,
    CulturalSensitivityLevel,
    FeedLayoutType,
    FeedType,
    InteractionType,
    LicenseType,
    ModerationDecision,
    ModerationStatus,
    SocialAccountStatus,
    SocialContentStatus,
    SocialContentType,
    SocialModerationStatus,
    SocialPlatform,
    SocialVisibility,
    SyncHealthStatus,
    SyncStatus,
)
from app.modules.social.domain.errors import (
    AccountNotAcceptedError,
    AccountSyncDisabledError,
    ContentNormalizationError,
    ProviderAuthenticationError,
    ProviderNotConfiguredError,
    ProviderRateLimitError,
    ProviderUnavailableError,
    SocialEngineError,
    SourceUrlError,
    UnsupportedPlatformError,
)
from app.modules.social.domain.models import (
    SocialAccount as DomainSocialAccount,
    SocialContent as DomainSocialContent,
    SocialCreator as DomainSocialCreator,
    SocialSyncState as DomainSocialSyncState,
)
from app.modules.social.domain.state_machines import (
    ContentStateMachine,
    CreatorStateMachine,
    CulturalConsentViolationError,
    InvalidStateTransitionError,
    SocialAccountStateMachine,
    calculate_content_expiration,
    validate_cultural_protection,
)
from app.modules.social.domain.value_objects import SourceUrl

__all__ = [
    "SocialPlatform",
    "SocialAccountStatus",
    "SocialContentType",
    "SocialContentStatus",
    "SocialModerationStatus",
    "SocialVisibility",
    "SyncStatus",
    "AccountAcceptanceAction",
    "SourceUrl",
    "DomainSocialAccount",
    "DomainSocialContent",
    "DomainSocialCreator",
    "DomainSocialSyncState",
    "SocialEngineError",
    "UnsupportedPlatformError",
    "ProviderNotConfiguredError",
    "AccountNotAcceptedError",
    "AccountSyncDisabledError",
    "SourceUrlError",
    "ProviderAuthenticationError",
    "ProviderRateLimitError",
    "ProviderUnavailableError",
    "ContentNormalizationError",
    "ContentType",
    "CreatorStatus",
    "ContentStatus",
    "ContentVisibility",
    "ModerationStatus",
    "ModerationDecision",
    "CulturalSensitivityLevel",
    "LicenseType",
    "FeedType",
    "InteractionType",
    "SyncHealthStatus",
    "FeedLayoutType",
    "CreatorStateMachine",
    "ContentStateMachine",
    "SocialAccountStateMachine",
    "InvalidStateTransitionError",
    "CulturalConsentViolationError",
    "validate_cultural_protection",
    "calculate_content_expiration",
]
