from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    CONTENT_PUBLISHED = "CONTENT_PUBLISHED"
    CONTENT_UPDATED = "CONTENT_UPDATED"
    CONTENT_UNPUBLISHED = "CONTENT_UNPUBLISHED"
    CONTENT_ARCHIVED = "CONTENT_ARCHIVED"

    TEMPLATE_PUBLISHED = "TEMPLATE_PUBLISHED"
    TEMPLATE_ROLLED_BACK = "TEMPLATE_ROLLED_BACK"

    CONTENT_DRIFT_DETECTED = "CONTENT_DRIFT_DETECTED"
