from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    CONTENT_PUBLISHED = "CONTENT_PUBLISHED"
    CONTENT_UPDATED = "CONTENT_UPDATED"
    CONTENT_UNPUBLISHED = "CONTENT_UNPUBLISHED"
    CONTENT_ARCHIVED = "CONTENT_ARCHIVED"

    TEMPLATE_PUBLISHED = "TEMPLATE_PUBLISHED"
    TEMPLATE_ROLLED_BACK = "TEMPLATE_ROLLED_BACK"

    CONTENT_DRIFT_DETECTED = "CONTENT_DRIFT_DETECTED"
    
    # Social & Feed Subsystem Events
    SOCIAL_ACCOUNT_REGISTERED = "SOCIAL_ACCOUNT_REGISTERED"
    SOCIAL_ACCOUNT_ACCEPTED = "SOCIAL_ACCOUNT_ACCEPTED"
    SOCIAL_ACCOUNT_ACTIVATED = "SOCIAL_ACCOUNT_ACTIVATED"
    SOCIAL_ACCOUNT_PAUSED = "SOCIAL_ACCOUNT_PAUSED"
    SOCIAL_CONTENT_CREATED = "SOCIAL_CONTENT_CREATED"
    SOCIAL_CONTENT_SUBMITTED = "SOCIAL_CONTENT_SUBMITTED"
    SOCIAL_CONTENT_MODERATED = "SOCIAL_CONTENT_MODERATED"
    SOCIAL_CONTENT_PUBLISHED = "SOCIAL_CONTENT_PUBLISHED"
    SOCIAL_CONTENT_UPDATED = "SOCIAL_CONTENT_UPDATED"
    SOCIAL_CONTENT_ARCHIVED = "SOCIAL_CONTENT_ARCHIVED"
    SOCIAL_CONTENT_SYNCED = "SOCIAL_CONTENT_SYNCED"
    SOCIAL_SYNC_COMPLETED = "SOCIAL_SYNC_COMPLETED"
    SOCIAL_SYNC_FAILED = "SOCIAL_SYNC_FAILED"
    SOCIAL_STORY_EXPIRED = "SOCIAL_STORY_EXPIRED"
    CREATOR_VERIFIED = "CREATOR_VERIFIED"
    CREATOR_UNVERIFIED = "CREATOR_UNVERIFIED"
    SOCIAL_INTERACTION_LIKE = "SOCIAL_INTERACTION_LIKE"
    SOCIAL_INTERACTION_UNLIKE = "SOCIAL_INTERACTION_UNLIKE"
    SOCIAL_INTERACTION_SAVE = "SOCIAL_INTERACTION_SAVE"
    SOCIAL_INTERACTION_UNSAVE = "SOCIAL_INTERACTION_UNSAVE"
    SOCIAL_INTERACTION_COMMENT = "SOCIAL_INTERACTION_COMMENT"
    SOCIAL_INTERACTION_SHARE = "SOCIAL_INTERACTION_SHARE"
    SOCIAL_INTERACTION_TRIP_ADD = "SOCIAL_INTERACTION_TRIP_ADD"
